[colors]
background = #282828
foreground = #ebdbb2
primary = #458588
alert = #fb4934
disabled = #928374
green = #98971a
red = #cc241d
purple = #b16286
aqua = #689d6a

[bar/main]

monitor = ${env:MONITOR:} 
# monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true

width = 100%
height = 34

offset-x = 0%
offset-y = 0%

; Background ARGB color (e.g. #f00, #ff992a, #ddff1023)
background = ${colors.background}

; Foreground ARGB color (e.g. #f00, #ff992a, #ddff1023)
foreground = ${colors.foreground}

radius-top = 0.0
radius-bottom = 0.0

line-size = 5
line-color = ${colors.background}

border-bottom-size = 0
border-bottom-color = ${colors.primary}

padding = 0

module-margin-left = 0
module-margin-right = 0

font-0 = "IosevkaTerm Nerd Font:size=10;4"
font-1 = "feather:size=10;3"

modules-left = launcher xworkspaces 
modules-center = playerctl-prev sep playerctl sep playerctl-next
modules-right = backlight sep pulseaudio sep battery sep temperature sep date sep power

; The separator will be inserted between the output of each module
separator =

; Opacity value between 0.0 and 1.0 used on fade in/out
dim-value = 1.0

; Value to be used to set the WM_NAME atom
; If the value is empty or undefined, the atom value
; will be created from the following template: polybar-[BAR]_[MONITOR]
; NOTE: The placeholders are not available for custom values
wm-name = 

; Locale used to localize various module data (e.g. date)
; Expects a valid libc locale, for example: sv_SE.UTF-8
locale = 

; Position of the system tray window
; If empty or undefined, tray support will be disabled
; NOTE: A center aligned tray will cover center aligned modules
;
; Available positions:
;   left
;   center
;   right
;   none
tray-position = right

; If true, the bar will not shift its
; contents when the tray changes
tray-detached = false

; Tray icon max size
tray-maxsize = 16

; Background color for the tray container 
; ARGB color (e.g. #f00, #ff992a, #ddff1023)
; By default the tray container will use the bar
; background color.
tray-background = ${colors.background}

; Tray offset defined as pixel value (e.g. 35) or percentage (e.g. 50%)
tray-offset-x = 0
tray-offset-y = 0

; Pad the sides of each tray icon
tray-padding = 0

; Scale factor for tray clients
tray-scale = 1.0

enable-ipc = true
ursor-scroll = 

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/sep]
type = custom/text
content = " | "

content-background = ${colors.background}
content-foreground = ${colors.foreground}

[module/launcher]
type = custom/text

content = "   "
content-font = 3
content-background = ${colors.background}
content-foreground = ${colors.green}
content-overline = ${colors.background}
content-underline = ${colors.background}

; "click-(left|middle|right)" will be executed using "/usr/bin/env sh -c $COMMAND"
click-left = ~/.config/polybar/scripts/launcher.sh &

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = true
interval = 5

format-volume = <ramp-volume>  <label-volume>

label-muted =  muted
label-muted-foreground = ${colors.disabled}

; Only applies if <ramp-volume> is used
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

click-right = pavucontrol

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP0
poll-interval = 2

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

format-charging = <label-charging>
format-charging-prefix = "󰢝"
format-charging-prefix-foreground = ${colors.primary}
format-charging-prefix-padding = 1
format-charging-overline = ${colors.background}
format-charging-underline = ${colors.background}

format-discharging = <label-discharging>
format-discharging-prefix = "󱟤"
format-discharging-prefix-foreground = ${colors.purple}
format-discharging-prefix-padding = 1
format-discharging-overline = ${colors.background}
format-discharging-underline = ${colors.background}

format-full = <label-full>
format-full-prefix = "󱊣"
format-full-prefix-foreground = ${colors.green}
format-full-prefix-padding = 1
format-full-overline = ${colors.background}
format-full-underline = ${colors.background}

label-charging = %percentage%%
label-charging-background = ${colors.background}
label-charging-padding = 1

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %percentage%%
label-discharging-background = ${colors.background}
label-discharging-padding = 1

; Available tokens:
;   %percentage% (default)
label-full = Full
label-full-background = ${colors.background}
label-full-padding = 1

[module/date]
type = internal/date

; Seconds to sleep between updates
interval = 1.0

; See "http://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
; NOTE: if you want to use syntax tags here you need to use %%{...}
;;date = %Y-%m-%d%

; Optional time format
time = "%I:%M %p"

; if `date-alt` or `time-alt` is defined, clicking
; the module will toggle between formats
;;date-alt = %A, %d %B %Y
time-alt = "%a, %d %b %Y"

; Available tags:
;   <label> (default)
format = <label>
format-prefix = 
format-prefix-background = ${colors.aqua}
format-prefix-padding = 1
format-overline = ${colors.background}
format-underline = ${colors.background}

; Available tokens:
;   %date%
;   %time%
; Default: %date%
label = %time%
label-background = ${colors.background}
label-padding = 1

[module/power]
type = custom/text

content = " ⏻ "
content-font = 3
content-background = ${colors.background}
content-foreground = ${colors.red}
content-overline = ${colors.background}
content-underline = ${colors.background}

click-left = rofi -show power-menu -modi power-menu:~/.local/bin/rofi-power-menu

[module/playerctl]
type = custom/script
exec = /home/besufikad/.config/polybar/scripts/playerctl.sh
interval = 0.5

[module/playerctl-prev]
type = custom/text
format = <label>
label = "󰒮"
click-left = playerctl previous
interval = 0.5

[module/playerctl-next]
type = custom/text
format = <label>
label = "󰒭"
click-left = playerctl next
interval = 0.5

[module/temperature]
type = internal/temperature

interval = 0.5

thermal-zone = 0
zone-type = x86_pkg_temp

hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input

; Base temperature for where to start the ramp (in degrees celsius)
; Default: 0
base-temperature = 20

; Threshold temperature to display warning label (in degrees celsius)
; Default: 80
warn-temperature = 80

format = <ramp> <label>

; Available tags:
;   <label-warn> (default)
;   <ramp>
format-warn = <ramp> <label-warn>

; Available tokens:
;   %temperature% (deprecated)
;   %temperature-c%   (default, temperature in °C)
;   %temperature-f%   (temperature in °F)
;   %temperature-k%   (temperature in Kelvin, new in version 3.7.0)
label = 󰔏 %temperature-c%

; Available tokens:
;   %temperature% (deprecated)
;   %temperature-c%   (default, temperature in °C)
;   %temperature-f%   (temperature in °F)
;   %temperature-k%   (temperature in Kelvin, new in version 3.7.0)
label-warn = 󰔏 %temperature-c%
label-warn-foreground = ${colors.red}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground}

[module/backlight]
;type = internal/xbacklight
type = internal/backlight
card = intel_backlight
enable-scroll = true

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp><label>
format-overline = ${colors.background}
format-underline = ${colors.background}

; Available tokens:
;   %percentage% (default)
label = %percentage%%
label-background = ${colors.background}
label-padding = 1

; Only applies if <ramp> is used
ramp-0 = 󰃝
ramp-1 = 󰃞
ramp-2 = 󰃟
ramp-3 = 󰃟
ramp-4 = 󰃠
ramp-background = ${colors.background}
ramp-padding = 1
